services:
  
  db:
    image: postgres:15
    container_name: crm_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  telegram_bot:
      # ▸ Весь репозиторий как build-context, но используем конкретный Dockerfile
      build:
        context: .
        dockerfile: telegram_bot/Dockerfile
      container_name: crm_telegram_bot
      depends_on:
        - db
      env_file:
        - telegram_bot/.env   # ← вот он
      
      restart: unless-stopped
      volumes:
        - "G:/Мой диск/Клиенты:/data/clients"
        - ./logs:/app/logs


volumes:
  db_data:
