services:
  
  db:
    image: postgres:15
    container_name: crm_db
    restart: unless-stopped
    env_file:
      - docker/db.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  telegram_bot:
      # ▸ Весь репозиторий как build-context, но используем конкретный Dockerfile
      build:
        context: .
        dockerfile: telegram_bot/Dockerfile
      container_name: crm_telegram_bot
      depends_on:
        - db
      env_file:
        - docker/bot.env
      restart: unless-stopped
      volumes:
        - ./logs:/app/logs


volumes:
  db_data:
