# ui/common/ru_headers.py

RU_HEADERS = {
    "payment_date": "Дата платежа",
    "actual_payment_date": "Оплачено фактически",
    "amount": "Сумма",
    "status": "Статус",
    "title": "Заголовок",
    "description": "Описание",
    "due_date": "Срок",
    "is_done": "Выполнено",
    "client": "Клиент",
    "deal": "Сделка",
    "policy": "Полис",
    "created_at": "Создано",
    "updated_at": "Обновлено",
    "income": "Поступление",
    "expense": "Расход",
    "type": "Тип",
    "category": "Категория",
    "company": "Компания",
    "actual_date": "Факт. дата",
    "commission_source": "Источник комиссии",
    "note": "Комментарий",
    "executor": "Исполнитель",
    "insurance_company": "Страховая компания",
    "insurance_type": "Вид страхования",
    "insured_amount": "Страховая сумма",
    "premium": "Страховая премия",
    "deductible": "Франшиза",
    "start_date": "Начало",
    "queued_at": "Отправлено",
    "dispatch_state": "Статус отправки",
    "reminder_date": "Напоминание",
    "calculations": "Расчёты",
    "is_closed": "Закрыто",
    "closed_reason": "Причина закрытия",
    "policy_number": "Номер полиса",
    "contractor": "Контрагент",
    "sales_channel": "Канал продаж",
    "vehicle_brand": "Марка",
    "vehicle_model": "Модель",
    "vehicle_vin": "VIN",
    "renewed_to": "Продлён до",
}
