"""Фасад, переэкспортирующий функции работы с задачами."""

from .task_crud import (
    add_task,
    build_task_query,
    get_all_tasks,
    get_incomplete_task,
    get_incomplete_tasks_by_deal,
    get_incomplete_tasks_for_executor,
    get_pending_tasks,
    get_pending_tasks_page,
    get_task_counts_by_deal_id,
    get_tasks_by_deal,
    get_tasks_page,
    mark_task_deleted,
    update_task,
)
from .task_queue import (
    get_all_deals_with_queued_tasks,
    get_all_queued_tasks,
    get_clients_with_queued_tasks,
    get_deals_with_queued_tasks,
    get_queued_tasks_by_deal,
    pop_all_by_deal,
    pop_next,
    pop_next_by_client,
    pop_next_by_deal,
    pop_task_by_id,
    queue_task,
    return_to_queue,
)
from .task_notifications import (
    append_note,
    link_telegram,
    mark_done,
    notify_task,
    unassign_from_telegram,
)
from services.deal_service import get_deal_by_id
from database.models import Client, Deal, Policy, Task


__all__ = [
    "add_task",
    "build_task_query",
    "get_all_tasks",
    "get_incomplete_task",
    "get_incomplete_tasks_by_deal",
    "get_incomplete_tasks_for_executor",
    "get_pending_tasks",
    "get_pending_tasks_page",
    "get_task_counts_by_deal_id",
    "get_tasks_by_deal",
    "get_tasks_page",
    "mark_task_deleted",
    "update_task",
    "get_all_deals_with_queued_tasks",
    "get_all_queued_tasks",
    "get_clients_with_queued_tasks",
    "get_deals_with_queued_tasks",
    "get_queued_tasks_by_deal",
    "pop_all_by_deal",
    "pop_next",
    "pop_next_by_client",
    "pop_next_by_deal",
    "pop_task_by_id",
    "queue_task",
    "return_to_queue",
    "append_note",
    "link_telegram",
    "mark_done",
    "notify_task",
    "unassign_from_telegram",
    "get_deal_by_id",
    "Task",
    "Client",
    "Deal",
    "Policy",
]

